// ═══════════════════════════════════════════════════════════════
// BACKEND 07: PRISMA ORM · SCHEMA DESIGN · RELATIONS · MIGRATIONS  (Day 42)
// Run: npx ts-node 07-prisma-orm.ts
// ═══════════════════════════════════════════════════════════════
//
// Prisma is a next-generation ORM for Node.js and TypeScript.
//
//  • Type-safe database access — the client is generated FROM your schema
//  • Single source of truth: schema.prisma drives models, migrations, AND types
//  • Works with PostgreSQL, MySQL, SQLite, MongoDB, CockroachDB, SQL Server
//  • Three tools in one: Prisma Client, Prisma Migrate, Prisma Studio
//
// The pattern: write schema → generate client → write queries in full TypeScript

// ───────────────────────────────────────────────────────────────
// 1. What Prisma Is — ORM vs Query Builder vs Raw SQL
// ───────────────────────────────────────────────────────────────

console.log("=== 1. What Prisma Is ===");

/*
  THREE LEVELS OF DATABASE ACCESS
  ────────────────────────────────
  Raw SQL (pg / mysql2)
    + Maximum control, maximum performance
    - No type safety, manual result typing, SQL injection risk, verbose
    e.g.  const res = await pool.query('SELECT * FROM users WHERE id = $1', [id])

  Query Builder (Knex, Drizzle)
    + Composable queries, some type safety, thin abstraction
    - You still think in SQL terms (JOIN, WHERE, SELECT)
    e.g.  knex('users').where('id', id).select('name', 'email')

  ORM — Object-Relational Mapper (Prisma, TypeORM, Sequelize)
    + Think in objects/models, not tables; relations are first-class
    + Generated TypeScript types — IDE autocomplete for every field
    + Handles migrations, seeding, studio UI
    - Slightly higher abstraction cost; complex queries may need raw fallback

  PRISMA'S THREE COMPONENTS
  ─────────────────────────
  1. Prisma Client  — the auto-generated, type-safe query builder
                      generated by: npx prisma generate
                      import { PrismaClient } from '@prisma/client'

  2. Prisma Migrate — schema migration tool
                      `prisma migrate dev`    → dev workflow (creates + applies)
                      `prisma migrate deploy` → CI/production (applies only)
                      `prisma db push`        → prototyping (no migration files)

  3. Prisma Studio  — visual GUI for browsing/editing data
                      run with: npx prisma studio
                      opens on http://localhost:5555

  HOW TYPE SAFETY WORKS
  ─────────────────────
  schema.prisma (your model definitions)
      ↓  npx prisma generate
  node_modules/@prisma/client (generated TS types)
      ↓  import into your app
  prisma.user.findUnique(...)  ← TypeScript knows every field and its type
*/

// Simulating what the generated Prisma Client types look like:
interface PrismaUser {
    id: string;
    username: string;
    passwordHash: string;
    firstName: string;
    lastName: string;
    createdAt: Date;
    updatedAt: Date;
}

interface PrismaAccount {
    id: string;
    balance: { toString(): string };   // Decimal object in real Prisma
    userId: string;
    createdAt: Date;
    updatedAt: Date;
}

console.log("Prisma Client provides full TypeScript types for every model field.");
console.log("This file demonstrates concepts; a real Prisma setup requires a database.\n");

// ───────────────────────────────────────────────────────────────
// 2. schema.prisma — The Single Source of Truth
// ───────────────────────────────────────────────────────────────

console.log("=== 2. schema.prisma Syntax ===");

/*
  A schema.prisma file has three sections:
    1. datasource — which database engine and connection string
    2. generator  — what to generate (almost always prisma-client-js)
    3. models     — your data tables / collections

  ─── DATASOURCE BLOCK ─────────────────────────────────────────
  datasource db {
    provider = "postgresql"        // or "mysql" | "sqlite" | "mongodb" | "sqlserver"
    url      = env("DATABASE_URL") // always read from env, NEVER hardcode
  }

  ─── GENERATOR BLOCK ──────────────────────────────────────────
  generator client {
    provider = "prisma-client-js"
    // output = "./generated/client"  // optional: custom output path
  }

  ─── MODEL SYNTAX ─────────────────────────────────────────────
  model User {
    id        String   @id @default(cuid())   // primary key
    email     String   @unique                // unique constraint
    name      String?                         // ? = optional (nullable)
    role      Role     @default(USER)         // enum default
    createdAt DateTime @default(now())        // DB-level default
    updatedAt DateTime @updatedAt             // auto-updated on every write

    posts     Post[]                          // relation field (not stored in DB)
  }

  ─── FIELD TYPES ──────────────────────────────────────────────
  String      → VARCHAR / TEXT
  Int         → INTEGER (32-bit)
  BigInt      → BIGINT (64-bit) — use for IDs from external systems
  Float       → DOUBLE PRECISION — imprecise, avoid for money
  Decimal     → NUMERIC — exact precision, use for money ✓
  Boolean     → BOOLEAN
  DateTime    → TIMESTAMP WITH TIME ZONE
  Json        → JSONB (postgres) — flexible blobs, no type safety inside
  Bytes       → BYTEA — binary data (file uploads stored in DB)

  ─── COMMON ATTRIBUTES ────────────────────────────────────────
  @id                        → primary key
  @unique                    → unique index on this column
  @default(value)            → default value
  @default(now())            → current timestamp at insert
  @default(autoincrement())  → integer PK that auto-increments (1, 2, 3…)
  @default(cuid())           → collision-resistant unique ID (e.g. "clx4y…")
  @default(uuid())           → UUID v4 (e.g. "550e8400-e29b-41d4-a716-…")
  @updatedAt                 → Prisma auto-sets on every update
  @map("column_name")        → rename the DB column (model field vs DB column)
  @db.Decimal(15, 2)         → DB-native type annotation (precision, scale)

  ─── MODEL-LEVEL ATTRIBUTES ───────────────────────────────────
  @@unique([field1, field2]) → composite unique constraint
  @@index([field1, field2])  → composite index (for query performance)
  @@map("table_name")        → rename the DB table

  ─── cuid() vs uuid() vs autoincrement() ─────────────────────
  autoincrement()  → 1, 2, 3… integers. Simple, but reveals record count.
                     Not safe for distributed systems (clashes at shard level).

  uuid()           → "550e8400-e29b-41d4-a716-446655440000"
                     RFC 4122 standard. Random, globally unique.
                     128 bits; slightly larger index than cuid.

  cuid()           → "clx4y2k0f0000qw9m3p0l7z8g"
                     Collision-resistant, URL-safe, roughly sortable by time.
                     Generally preferred in Prisma projects.

  PAYTM SCHEMA REFERENCE (paytm/backend/prisma/schema.prisma)
  ─────────────────────────────────────────────────────────────
  The Paytm project uses:
    • cuid() for all @id fields            (User.id, Account.id, Transaction.id)
    • Decimal @db.Decimal(15, 2)           (Account.balance, Transaction.amount)
    • @updatedAt                           (User.updatedAt, Account.updatedAt)
    • @unique on Account.userId            (enforces one account per user)
    • Named relations via @relation("...")  (SentTransactions, ReceivedTransactions)
*/

// Demonstrating the cuid vs uuid distinction conceptually:
function fakeCuid(): string {
    // Real cuid looks like: clx4y2k0f0000qw9m3p0l7z8g
    // Starts with 'c', time-based prefix, then random suffix
    return "cl" + Math.random().toString(36).slice(2, 20);
}

function fakeUuid(): string {
    // Real UUID: 550e8400-e29b-41d4-a716-446655440000
    const hex = () => Math.floor(Math.random() * 0xffff).toString(16).padStart(4, "0");
    return `${hex()}${hex()}-${hex()}-4${hex().slice(1)}-${hex()}-${hex()}${hex()}${hex()}`;
}

console.log("cuid() example:", fakeCuid());
console.log("uuid() example:", fakeUuid());
console.log("autoincrement(): 1, 2, 3, 4, 5 …\n");

// ───────────────────────────────────────────────────────────────
// 3. Relations — One-to-One, One-to-Many, Many-to-Many
// ───────────────────────────────────────────────────────────────

console.log("=== 3. Relations ===");

/*
  PRISMA RELATION ANATOMY
  ────────────────────────
  Every relation requires:
    1. A relation field   (virtual — not stored in DB, just for Prisma queries)
    2. A scalar FK field  (real column stored in DB)
    3. @relation() directive linking them

  ─── ONE-TO-ONE: User → Account ─────────────────────────────
  (From paytm schema — one User has exactly one Account)

  model User {
    id      String   @id @default(cuid())
    account Account?          // ← relation field, nullable (user may have no account)
  }

  model Account {
    id     String @id @default(cuid())
    userId String @unique      // ← scalar FK — @unique enforces 1-to-1
    user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)
    //           @relation tells Prisma: userId column → User.id column
    //           onDelete: Cascade → deleting User also deletes Account
  }

  ─── ONE-TO-MANY: User → Posts ──────────────────────────────
  One User can write many Posts. Each Post belongs to one User.

  model User {
    id    String @id @default(cuid())
    posts Post[]              // ← relation field (array = many)
  }

  model Post {
    id       String @id @default(cuid())
    authorId String           // ← scalar FK
    author   User   @relation(fields: [authorId], references: [id])
    //       no @unique here → one user can have many posts
  }

  ─── ONE-TO-MANY WITH NAMED RELATIONS (Paytm) ───────────────
  When a model appears TWICE in relations to the same target,
  you MUST name them to disambiguate.

  model User {
    sentTxns     Transaction[] @relation("SentTransactions")
    receivedTxns Transaction[] @relation("ReceivedTransactions")
  }

  model Transaction {
    senderId   String
    sender     User @relation("SentTransactions",   fields: [senderId],   references: [id])
    receiverId String
    receiver   User @relation("ReceivedTransactions", fields: [receiverId], references: [id])
  }

  ─── MANY-TO-MANY (IMPLICIT) ─────────────────────────────────
  Prisma creates a hidden join table automatically.
  Good for simple M:N where you don't need extra fields on the join.

  model Post {
    id   String @id @default(cuid())
    tags Tag[]
  }

  model Tag {
    id    String @id @default(cuid())
    name  String @unique
    posts Post[]
  }
  // Prisma creates _PostToTag(A: postId, B: tagId) behind the scenes

  ─── MANY-TO-MANY (EXPLICIT JUNCTION) ────────────────────────
  Use when you need extra data on the join (e.g., "assignedAt", "role").

  model Post {
    id          String       @id @default(cuid())
    postTags    PostTag[]
  }

  model Tag {
    id       String    @id @default(cuid())
    name     String    @unique
    postTags PostTag[]
  }

  model PostTag {
    postId     String
    tagId      String
    assignedAt DateTime @default(now())
    assignedBy String   // extra field — only possible with explicit junction

    post Post @relation(fields: [postId], references: [id])
    tag  Tag  @relation(fields: [tagId],  references: [id])

    @@id([postId, tagId])  // composite PK
  }

  ─── REQUIRED vs OPTIONAL RELATIONS ─────────────────────────
  model Post {
    authorId String     // required FK → author MUST exist
    author   User   @relation(fields: [authorId], references: [id])

    editorId String?    // optional FK → editor may be null
    editor   User?  @relation("PostEditor", fields: [editorId], references: [id])
  }

  ─── onDelete BEHAVIOUR ──────────────────────────────────────
  onDelete: Cascade   → delete child when parent is deleted (Account, Transaction)
  onDelete: Restrict  → prevent parent deletion if children exist (DEFAULT)
  onDelete: SetNull   → set FK to null on parent deletion (FK must be optional)
  onDelete: NoAction  → database decides (similar to Restrict but deferred)
*/

// Demonstrating relation traversal in pseudo-queries:
interface PostModel {
    id: string;
    title: string;
    authorId: string;
    author?: PrismaUser;
    tags?: TagModel[];
}

interface TagModel {
    id: string;
    name: string;
    posts?: PostModel[];
}

function demonstrateRelations(): void {
    const post: PostModel = {
        id: "cl123",
        title: "Learning Prisma",
        authorId: "cl456",
        author: {
            id: "cl456",
            username: "sadik",
            passwordHash: "hashed",
            firstName: "Sadik",
            lastName: "Shaikh",
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        tags: [
            { id: "t1", name: "prisma" },
            { id: "t2", name: "backend" },
        ],
    };

    console.log("Post with included relations:");
    console.log(`  Title: ${post.title}`);
    console.log(`  Author: ${post.author?.firstName} ${post.author?.lastName}`);
    console.log(`  Tags: ${post.tags?.map(t => t.name).join(", ")}`);
}

demonstrateRelations();
console.log();

// ───────────────────────────────────────────────────────────────
// 4. Migrations
// ───────────────────────────────────────────────────────────────

console.log("=== 4. Migrations ===");

/*
  WHAT A MIGRATION IS
  ───────────────────
  A migration is a versioned SQL file that describes how the database schema
  changes from one state to the next. Prisma generates these automatically
  by diffing your current schema.prisma against the current DB state.

  MIGRATION FILES LIVE IN:
    prisma/migrations/
    ├── 20240101120000_init/
    │   └── migration.sql       ← auto-generated SQL
    ├── 20240102093000_add_posts/
    │   └── migration.sql
    └── migration_lock.toml     ← locks the DB provider (don't delete)

  TRACKING TABLE:
    Prisma creates `_prisma_migrations` in your DB automatically.
    It records which migrations have been applied, when, and whether they
    failed. Never manually edit this table.

  ─── npx prisma migrate dev ──────────────────────────────────
  Use during LOCAL development.

  What it does:
    1. Detects drift between schema.prisma and the current DB
    2. Generates a new migration.sql file in prisma/migrations/
    3. Applies the migration to the dev DB
    4. Re-runs `prisma generate` to update the client types
    5. Prompts for a migration name (e.g., "add_posts_table")

  Example:
    $ npx prisma migrate dev --name add_posts_table
    ✔ Generated migration 20240102_add_posts_table
    ✔ Applied migration
    ✔ Generated Prisma Client

  ─── npx prisma migrate deploy ───────────────────────────────
  Use in CI/CD and production.

  What it does:
    1. Reads pending migrations from prisma/migrations/
    2. Applies them in order — NO generation, NO prompts, NO drift detection
    3. Fails loudly if a migration has been edited after it was applied

  Key difference from `migrate dev`:
    • Never creates new migration files
    • Never generates the client
    • Safe for automated pipelines — deterministic, no user input needed

  Example in Dockerfile / CI:
    RUN npx prisma migrate deploy
    RUN node dist/server.js

  ─── npx prisma db push ──────────────────────────────────────
  Use for RAPID PROTOTYPING (schema exploration, hackathons).

  What it does:
    • Pushes schema.prisma directly to the DB WITHOUT creating migration files
    • Regenerates the Prisma Client

  Tradeoffs:
    ✓ Fast iteration — no migration files to manage
    ✗ Destructive if you remove/rename fields (no safety prompts)
    ✗ Cannot be deployed to production in a safe, repeatable way
    ✗ No migration history — can't reproduce the schema on a fresh DB

  ─── SQUASHING MIGRATIONS ────────────────────────────────────
  If you have hundreds of old migrations slowing down `migrate deploy`,
  you can squash them:

    $ npx prisma migrate squash --experimental
    # (or manually: delete old migrations, create one new "baseline" migration)

  Workflow for squashing in production:
    1. Take a DB dump as backup
    2. Delete old migration folders
    3. Run `prisma migrate resolve --applied <new_baseline_name>` on each
       existing production DB to mark it as already applied
    4. From now on, new `migrate deploy` runs only see new migrations

  ─── ROLLING BACK ────────────────────────────────────────────
  Prisma does NOT have a built-in rollback command.
  Options:
    1. Write a new "down" migration manually and apply it
    2. Restore DB from backup (safest for production disasters)
    3. Use `prisma migrate resolve --rolled-back <migration_name>` to mark
       a failed migration as rolled back in _prisma_migrations without re-running it
*/

function explainMigrationCommands(): void {
    const commands: Record<string, string> = {
        "prisma migrate dev":     "Dev only — generate + apply + generate client",
        "prisma migrate deploy":  "Prod/CI — apply pending migrations only, no prompts",
        "prisma db push":         "Prototyping — push schema without migration files",
        "prisma migrate status":  "Show which migrations are applied vs pending",
        "prisma migrate reset":   "Drop DB + re-apply all migrations (dev only, destructive)",
        "prisma studio":          "Open GUI at localhost:5555",
        "prisma generate":        "Re-generate Prisma Client from schema",
        "prisma format":          "Auto-format schema.prisma",
    };

    console.log("Prisma CLI commands:");
    for (const [cmd, description] of Object.entries(commands)) {
        console.log(`  npx ${cmd.padEnd(30)} → ${description}`);
    }
}

explainMigrationCommands();
console.log();

// ───────────────────────────────────────────────────────────────
// 5. Prisma Client CRUD
// ───────────────────────────────────────────────────────────────

console.log("=== 5. Prisma Client CRUD ===");

/*
  In a real app you import and use the client:
    import { PrismaClient } from '@prisma/client';
    const prisma = new PrismaClient();

  All Prisma Client methods return Promises. Use async/await.
*/

// We simulate the API calls with typed pseudo-code to teach the shape:

interface QueryResult<T> {
    operation: string;
    query: string;
    result: T;
}

function showQuery<T>(operation: string, query: string, result: T): QueryResult<T> {
    return { operation, query, result };
}

// ── FIND OPERATIONS ──────────────────────────────────────────────
const reads = [
    showQuery(
        "findUnique",
        `prisma.user.findUnique({ where: { id: "cl123" } })`,
        { id: "cl123", username: "sadik", firstName: "Sadik", lastName: "Shaikh" }
    ),
    showQuery(
        "findUnique — select sparse fields",
        `prisma.user.findUnique({ where: { id: "cl123" }, select: { firstName: true, lastName: true } })`,
        { firstName: "Sadik", lastName: "Shaikh" }
    ),
    showQuery(
        "findFirst",
        `prisma.user.findFirst({ where: { firstName: { startsWith: "S" } }, orderBy: { createdAt: "desc" } })`,
        { id: "cl456", username: "sara", firstName: "Sara", lastName: "Khan" }
    ),
    showQuery(
        "findMany — filter + pagination",
        `prisma.user.findMany({ where: { OR: [{ firstName: "Sadik" }, { username: { contains: "admin" } }] }, take: 10, skip: 0 })`,
        [{ id: "cl123", username: "sadik" }, { id: "cl789", username: "admin_user" }]
    ),
];

console.log("READ operations:");
for (const q of reads) {
    console.log(`  [${q.operation}]`);
    console.log(`    ${q.query}`);
    console.log(`    → ${JSON.stringify(q.result)}`);
}

/*
  WHERE CLAUSE OPERATORS
  ───────────────────────
  equals:      { where: { name: { equals: "Sadik" } } }        (or shorthand: { name: "Sadik" })
  not:         { where: { name: { not: "Sadik" } } }
  in:          { where: { id: { in: ["id1", "id2"] } } }
  notIn:       { where: { id: { notIn: ["id1"] } } }
  lt/lte:      { where: { age: { lte: 30 } } }
  gt/gte:      { where: { balance: { gte: 1000 } } }
  contains:    { where: { name: { contains: "sad", mode: "insensitive" } } }
  startsWith:  { where: { email: { startsWith: "sadik" } } }
  endsWith:    { where: { email: { endsWith: "@gmail.com" } } }
  AND:         { where: { AND: [{ age: { gte: 18 } }, { active: true }] } }
  OR:          { where: { OR: [{ role: "admin" }, { role: "superadmin" }] } }
  NOT:         { where: { NOT: { deletedAt: null } } }
*/

console.log();

// ── WRITE OPERATIONS ──────────────────────────────────────────────
/*
  CREATE
  ──────
  await prisma.user.create({
    data: {
      username: "sadik",
      passwordHash: "hashed_password",
      firstName: "Sadik",
      lastName: "Shaikh",
      // Nested create — create related Account at the same time:
      account: {
        create: { balance: 1000 }
      }
    }
  });

  CREATE MANY
  ───────────
  await prisma.user.createMany({
    data: [
      { username: "user1", passwordHash: "h1", firstName: "A", lastName: "B" },
      { username: "user2", passwordHash: "h2", firstName: "C", lastName: "D" },
    ],
    skipDuplicates: true,  // ignore rows that violate unique constraints
  });

  UPDATE
  ──────
  await prisma.account.update({
    where: { userId: "cl123" },
    data: {
      balance: { increment: 500 },     // atomic increment
      // decrement, multiply, divide also available
    }
  });

  UPDATE MANY
  ───────────
  await prisma.user.updateMany({
    where: { createdAt: { lt: new Date('2023-01-01') } },
    data: { role: "ARCHIVED" }
  });

  UPSERT — create if not exists, update if exists
  ──────────────────────────────────────────────
  await prisma.user.upsert({
    where: { username: "sadik" },
    update: { firstName: "Sadik Updated" },
    create: { username: "sadik", firstName: "Sadik", lastName: "S", passwordHash: "h" }
  });

  DELETE
  ──────
  await prisma.user.delete({ where: { id: "cl123" } });

  DELETE MANY
  ───────────
  await prisma.user.deleteMany({ where: { deletedAt: { not: null } } });
*/

function demonstrateCrud(): void {
    console.log("WRITE operation shapes (pseudo-code):");
    const ops = [
        "prisma.user.create({ data: { username, passwordHash, firstName, lastName } })",
        "prisma.user.createMany({ data: [...], skipDuplicates: true })",
        "prisma.account.update({ where: { userId }, data: { balance: { increment: 500 } } })",
        "prisma.user.upsert({ where: { username }, update: {...}, create: {...} })",
        "prisma.user.delete({ where: { id } })",
        "prisma.user.deleteMany({ where: { deletedAt: { not: null } } })",
    ];
    for (const op of ops) {
        console.log(`  await ${op}`);
    }
}

demonstrateCrud();

/*
  SELECT vs INCLUDE
  ─────────────────
  select  → sparse selection — return ONLY the fields you name
            Use to avoid over-fetching. Nested select works on relations too.
            prisma.user.findUnique({
              where: { id },
              select: { firstName: true, lastName: true }
              // Result has NO id, createdAt, passwordHash, etc.
            })

  include → eager-load relations — return all model fields PLUS the relation
            prisma.user.findUnique({
              where: { id },
              include: { account: true, sentTxns: true }
              // Result has ALL User fields + account object + sentTxns array
            })

  You CANNOT use select and include on the same level.
  But you CAN nest select inside include:
    prisma.transaction.findMany({
      include: {
        sender:   { select: { firstName: true, lastName: true } },
        receiver: { select: { firstName: true, lastName: true } },
      }
    })
  This is exactly how paytm/backend/routes/account.js fetches transactions.
*/

console.log();

// ───────────────────────────────────────────────────────────────
// 6. Transactions
// ───────────────────────────────────────────────────────────────

console.log("=== 6. Transactions ===");

/*
  A database transaction groups multiple operations so they either ALL succeed
  or ALL fail together. This is the ACID guarantee (Atomicity).

  Without a transaction in a money transfer:
    Step 1: Debit sender's account   ← succeeds
    Step 2: Credit receiver's account ← DATABASE CRASH
    Result: Money has vanished. Sender is debited, receiver never credited.

  With a transaction:
    Step 1: Debit  (within transaction)
    Step 2: Credit (within transaction)
    CRASH → entire transaction is rolled back. Sender keeps their money.

  PRISMA OFFERS TWO TRANSACTION STYLES
  ──────────────────────────────────────

  STYLE 1: Sequential (batch) transactions
  ─────────────────────────────────────────
  Pass an array of Prisma calls. Prisma wraps them in a single transaction.
  All calls are prepared BEFORE being sent to the DB.

  const [updatedUser, newPost] = await prisma.$transaction([
    prisma.user.update({ where: { id }, data: { name: "New Name" } }),
    prisma.post.create({ data: { title: "Hello", authorId: id } }),
  ]);

  Limitation: You cannot use the result of one operation as input to the next.
  They are all constructed before any runs.

  STYLE 2: Interactive transactions
  ──────────────────────────────────
  Pass an async callback that receives a `tx` client. Operations run
  sequentially inside the transaction. You CAN read results mid-transaction.

  await prisma.$transaction(async (tx) => {
    const sender = await tx.account.findUnique({ where: { userId: senderId } });
    if (sender.balance < amount) throw new Error("INSUFFICIENT_BALANCE");

    await tx.account.update({ where: { userId: senderId }, data: { balance: { decrement: amount } } });
    await tx.account.update({ where: { userId: receiverId }, data: { balance: { increment: amount } } });
    await tx.transaction.create({ data: { senderId, receiverId, amount } });
    // If ANY line above throws, ALL three operations are rolled back
  });

  Use interactive transactions when:
    ✓ You need to READ data mid-transaction and branch on it
    ✓ You need the result of step N to construct step N+1
    ✓ You need to validate a condition (e.g., sufficient balance) mid-flight

  Use sequential transactions when:
    ✓ Operations are independent and pre-defined
    ✓ You just need atomicity without conditional logic
    ✓ You want slightly less overhead (no round-trips mid-transaction)
*/

// Paytm transfer — annotated version of paytm/backend/routes/account.js:
async function simulatePaytmTransfer(
    senderId: string,
    receiverId: string,
    amount: number,
    note?: string
): Promise<{ success: boolean; message: string }> {
    console.log(`\nSimulating transfer: ${senderId} → ${receiverId}, ₹${amount}`);

    // In real code:
    // await prisma.$transaction(async (tx) => {
    //
    //   // STEP 1: Read sender's balance inside the transaction
    //   // (reading INSIDE the tx ensures we see committed-only data —
    //   //  no phantom reads from concurrent transfers)
    //   const senderAccount = await tx.account.findUnique({
    //     where: { userId: senderId }
    //   });
    //
    //   if (!senderAccount || Number(senderAccount.balance) < amount) {
    //     throw new Error("INSUFFICIENT_BALANCE");
    //     // throwing inside $transaction → auto rollback
    //   }
    //
    //   // STEP 2: Debit sender
    //   await tx.account.update({
    //     where: { userId: senderId },
    //     data: { balance: { decrement: amount } }
    //   });
    //
    //   // STEP 3: Credit receiver
    //   await tx.account.update({
    //     where: { userId: receiverId },
    //     data: { balance: { increment: amount } }
    //   });
    //
    //   // STEP 4: Record the transaction
    //   await tx.transaction.create({
    //     data: { senderId, receiverId, amount, note: note ?? null }
    //   });
    //
    //   // All 3 writes committed atomically.
    // });

    // Simulation (no real DB):
    const senderBalance = 500;
    if (senderBalance < amount) {
        return { success: false, message: "Insufficient balance — transaction rolled back" };
    }
    const steps = [
        `  [tx] Debit  ${senderId}: balance ${senderBalance} → ${senderBalance - amount}`,
        `  [tx] Credit ${receiverId}: balance increased by ${amount}`,
        `  [tx] Transaction record created${note ? ` (note: "${note}")` : ""}`,
        "  [tx] COMMIT — all 3 operations persisted atomically",
    ];
    steps.forEach(s => console.log(s));
    return { success: true, message: "Transfer successful" };
}

// Run the simulation:
(async () => {
    const result = await simulatePaytmTransfer("user_sadik", "user_sara", 200, "Lunch split");
    console.log("Result:", result.message);

    const failResult = await simulatePaytmTransfer("user_sadik", "user_sara", 1000);
    console.log("Result:", failResult.message);
    console.log();
})();

// ───────────────────────────────────────────────────────────────
// 7. Advanced Queries
// ───────────────────────────────────────────────────────────────

console.log("=== 7. Advanced Queries ===");

/*
  ─── orderBy ──────────────────────────────────────────────────
  // Single field:
  prisma.user.findMany({ orderBy: { createdAt: "desc" } })

  // Multiple fields (primary sort, then tiebreaker):
  prisma.post.findMany({
    orderBy: [{ publishedAt: "desc" }, { title: "asc" }]
  })

  ─── OFFSET PAGINATION (take + skip) ─────────────────────────
  const PAGE_SIZE = 20;
  const page = 3; // 0-indexed

  const users = await prisma.user.findMany({
    take: PAGE_SIZE,
    skip: page * PAGE_SIZE,
    orderBy: { createdAt: "desc" }
  });

  Tradeoff: Slow on large datasets because the DB must scan & skip all prior rows.

  ─── CURSOR PAGINATION (better for large tables) ─────────────
  // First page:
  const firstPage = await prisma.user.findMany({
    take: 20,
    orderBy: { id: "asc" }
  });
  const lastUser = firstPage[firstPage.length - 1];

  // Next page (starts AFTER the cursor):
  const nextPage = await prisma.user.findMany({
    take: 20,
    skip: 1,                        // skip the cursor itself
    cursor: { id: lastUser.id },    // start from here
    orderBy: { id: "asc" }
  });

  Advantage: Consistent performance regardless of table size.
  Tradeoff: Can't jump to page 5 — must follow the chain.

  ─── distinct ────────────────────────────────────────────────
  // Get unique first names only:
  prisma.user.findMany({
    distinct: ["firstName"],
    select: { firstName: true }
  })

  ─── AGGREGATIONS ────────────────────────────────────────────
  // Count + Sum + Avg:
  const stats = await prisma.account.aggregate({
    _count: { id: true },
    _sum:   { balance: true },
    _avg:   { balance: true },
    _min:   { balance: true },
    _max:   { balance: true },
    where:  { balance: { gt: 0 } }
  });
  // stats._sum.balance → total balance across all accounts
  // stats._count.id    → number of accounts

  ─── groupBy ─────────────────────────────────────────────────
  // Transaction totals sent by each user:
  const totals = await prisma.transaction.groupBy({
    by: ["senderId"],
    _sum:   { amount: true },
    _count: { id: true },
    orderBy: { _sum: { amount: "desc" } },
    having: { amount: { _sum: { gt: 1000 } } }  // like SQL HAVING
  });
  // Returns: [{ senderId: "cl123", _sum: { amount: 5000 }, _count: { id: 12 } }, ...]
*/

function demonstrateAdvancedQueries(): void {
    console.log("Advanced query patterns:");

    const patterns: Array<{ name: string; example: string }> = [
        {
            name: "Offset pagination",
            example: "prisma.user.findMany({ take: 20, skip: page * 20, orderBy: { createdAt: 'desc' } })",
        },
        {
            name: "Cursor pagination",
            example: "prisma.user.findMany({ take: 20, skip: 1, cursor: { id: lastId }, orderBy: { id: 'asc' } })",
        },
        {
            name: "Distinct",
            example: "prisma.user.findMany({ distinct: ['firstName'], select: { firstName: true } })",
        },
        {
            name: "Aggregate",
            example: "prisma.account.aggregate({ _sum: { balance: true }, _count: { id: true } })",
        },
        {
            name: "GroupBy",
            example: "prisma.transaction.groupBy({ by: ['senderId'], _sum: { amount: true }, orderBy: { _sum: { amount: 'desc' } } })",
        },
        {
            name: "Multi-sort",
            example: "prisma.post.findMany({ orderBy: [{ publishedAt: 'desc' }, { title: 'asc' }] })",
        },
    ];

    for (const p of patterns) {
        console.log(`  [${p.name}]`);
        console.log(`    await ${p.example}`);
    }
}

demonstrateAdvancedQueries();
console.log();

// ───────────────────────────────────────────────────────────────
// 8. Prisma in Production
// ───────────────────────────────────────────────────────────────

console.log("=== 8. Prisma in Production ===");

/*
  ─── SINGLETON PATTERN ────────────────────────────────────────
  PrismaClient opens a connection pool when instantiated.
  Creating one instance per request = connection exhaustion under load.
  Solution: create ONE instance per process and reuse it.

  // lib/prisma.ts
  import { PrismaClient } from '@prisma/client';

  declare global {
    var __prisma: PrismaClient | undefined;
  }

  const prisma: PrismaClient =
    global.__prisma ?? new PrismaClient({ log: ['error'] });

  if (process.env.NODE_ENV !== 'production') {
    // In development, HMR (hot reload) creates new module instances.
    // Storing on global prevents creating a new client on every reload.
    global.__prisma = prisma;
  }

  export default prisma;

  This is what paytm/backend/prisma/client.js should look like.

  ─── CONNECTION POOLING ───────────────────────────────────────
  Problem: Serverless functions (Vercel, AWS Lambda) can spawn hundreds
  of instances, each opening its own DB connection. PostgreSQL has a hard
  connection limit (typically 100–500). You'll hit "too many connections".

  Solution: PgBouncer (connection pooler) sits between your app and Postgres.
  Many app connections → few real DB connections (pool).

  In schema.prisma datasource:
    url = env("DATABASE_URL")  // append ?pgbouncer=true for PgBouncer
    directUrl = env("DIRECT_URL")  // used by Migrate (bypasses PgBouncer)

  Prisma also ships Accelerate (prisma.io/accelerate) — a managed
  connection pooler + global cache, zero-config.

  ─── DISCONNECT IN TESTS ──────────────────────────────────────
  After each test suite, call prisma.$disconnect() so Jest can exit cleanly:

  afterAll(async () => {
    await prisma.$disconnect();
  });

  ─── LOGGING ──────────────────────────────────────────────────
  new PrismaClient({
    log: [
      { emit: 'event', level: 'query' },  // raw SQL + params + duration
      { emit: 'stdout', level: 'error' },
      { emit: 'stdout', level: 'warn' },
    ]
  });

  prisma.$on('query', (e) => {
    console.log('Query:', e.query);
    console.log('Params:', e.params);
    console.log('Duration:', e.duration + 'ms');
  });

  Enable during development to see what SQL Prisma generates.
  Disable or restrict to 'error' in production to avoid log bloat.

  ─── SOFT DELETES WITH MIDDLEWARE ─────────────────────────────
  "Soft delete" means marking a record as deleted (deletedAt = new Date())
  instead of physically removing it. Useful for audit trails and recovery.

  prisma.$use(async (params, next) => {
    // Intercept delete → convert to update
    if (params.action === 'delete') {
      params.action = 'update';
      params.args.data = { deletedAt: new Date() };
    }
    if (params.action === 'deleteMany') {
      params.action = 'updateMany';
      params.args.data = { deletedAt: new Date() };
    }

    // Intercept reads → exclude soft-deleted records
    if (params.action === 'findMany' || params.action === 'findFirst') {
      params.args.where = {
        ...params.args.where,
        deletedAt: null
      };
    }

    return next(params);
  });

  Note: Prisma $use middleware is deprecated in v5+ in favour of
  Prisma Client Extensions — same concept, better DX.
*/

function demonstrateProductionPatterns(): void {
    console.log("Production checklist:");
    const checklist = [
        ["Singleton PrismaClient",      "One instance per process — prevents connection exhaustion"],
        ["Connection pooling",          "PgBouncer or Prisma Accelerate for serverless environments"],
        ["$disconnect in tests",        "afterAll(() => prisma.$disconnect()) — lets Jest exit cleanly"],
        ["Logging config",              "log: ['query'] in dev, log: ['error'] in prod"],
        ["Soft deletes via middleware", "Convert delete → update({ deletedAt: new Date() })"],
        ["migrate deploy in CI",        "Never `migrate dev` in CI — no prompts, no drift detection"],
        ["directUrl for migrations",    "Bypass PgBouncer for migrate operations (PgBouncer breaks DDL)"],
    ];

    for (const [pattern, detail] of checklist) {
        console.log(`  ✓ ${pattern}`);
        console.log(`      ${detail}`);
    }
}

demonstrateProductionPatterns();
console.log();

// ───────────────────────────────────────────────────────────────
// PRACTICE
// ───────────────────────────────────────────────────────────────

console.log("=== Practice ===");

// Q1: What's the difference between `prisma migrate dev` and `prisma migrate deploy`?
// migrate dev:
//   - For LOCAL development only
//   - Detects schema drift, generates a new migration.sql file, applies it, re-generates client
//   - Interactive: prompts you for a migration name
//   - Can reset the DB (prisma migrate reset)
//
// migrate deploy:
//   - For CI/CD and PRODUCTION
//   - Only applies migrations that already exist in prisma/migrations/
//   - Never generates new migration files, never generates the client, no prompts
//   - Deterministic and safe for automated pipelines
//   - Fails if a previously-applied migration file has been edited
//
// Rule: dev creates, deploy applies. Never run `migrate dev` in production.

console.log("Q1: migrate dev = generates + applies (dev only).");
console.log("    migrate deploy = applies existing migrations only (prod/CI).\n");

// Q2: How do you model a many-to-many relationship between Post and Tag?
//
// IMPLICIT (Prisma manages the join table):
//   model Post { id String @id; tags Tag[] }
//   model Tag  { id String @id; name String @unique; posts Post[] }
//   → Prisma creates _PostToTag(A, B) table automatically
//
// EXPLICIT (you define the join table — required when you need extra fields):
//   model Post    { id String @id; postTags PostTag[] }
//   model Tag     { id String @id; postTags PostTag[] }
//   model PostTag {
//     postId     String
//     tagId      String
//     assignedAt DateTime @default(now())
//     post Post @relation(fields: [postId], references: [id])
//     tag  Tag  @relation(fields: [tagId],  references: [id])
//     @@id([postId, tagId])
//   }

console.log("Q2: Implicit M:N uses Post[] / Tag[] on both sides.");
console.log("    Explicit M:N uses a PostTag junction model with @@id([postId, tagId]).\n");

// Q3: Why should you use `Decimal` instead of `Float` for money fields?
//
// Float is stored as IEEE 754 floating-point — it cannot represent most decimal
// fractions exactly. For example:
//   0.1 + 0.2 in IEEE 754 = 0.30000000000000004
// In a financial system this means:
//   balance 1000.00 - 0.10 might produce 999.9000000000001
//   Over millions of transactions, these rounding errors accumulate and
//   cause real money discrepancies.
//
// Decimal stores numbers as exact decimal strings with a defined precision
// and scale (e.g., Decimal(15, 2) = up to 15 total digits, 2 after decimal).
// 1000.00 - 0.10 = 999.90 exactly. Always.
//
// The Paytm schema uses: balance Decimal @db.Decimal(15, 2)
// This means balances are always stored with exactly 2 decimal places,
// supporting up to ₹9,999,999,999,999.99

const floatErr = 0.1 + 0.2;
console.log(`Q3: Float: 0.1 + 0.2 = ${floatErr} (precision error!)`);
console.log("    Decimal avoids this — exact arithmetic, critical for money.");
console.log("    Paytm schema: balance Decimal @db.Decimal(15, 2)\n");

// Q4: In a transfer operation, why must the debit and credit happen in a transaction?
//
// Without a transaction, a failure between the two operations leaves the system
// in an inconsistent state:
//
// Thread A: Debit sender (-₹500)  ← stored
//   *** Server crash / network error / exception ***
// Thread A: Credit receiver       ← NEVER executes
//
// Result: ₹500 has been destroyed. The sender is poorer, the receiver is not richer.
// No amount of retry logic can fix this safely after the fact.
//
// With a transaction (as in paytm/backend/routes/account.js):
//   The debit, credit, and Transaction record creation are ONE atomic unit.
//   If any step throws an error, the entire transaction is rolled back to the
//   state before the first operation. The DB remains consistent.
//
// Additional benefit: Prisma's interactive transaction reads the balance INSIDE
// the transaction, preventing a race condition where two concurrent transfers
// both see the old balance as sufficient and both proceed.

console.log("Q4: Without a transaction, a crash between debit and credit destroys money.");
console.log("    A transaction is atomic — all 3 ops (debit, credit, log) succeed or all fail.\n");

// Q5: What's the difference between `select` and `include` in a Prisma query?
//
// select  → pick ONLY the fields you explicitly list. Relations become
//            unavailable unless you nest a select inside.
//            { select: { firstName: true, lastName: true } }
//            Result: { firstName: "Sadik", lastName: "Shaikh" }
//            No id, no createdAt, no passwordHash.
//            Use to minimise data transferred from DB (sparse projection).
//
// include → return ALL fields of the model AND additionally load the
//            specified relations. Relations not listed are NOT loaded.
//            { include: { account: true } }
//            Result: { id, username, firstName, ..., account: { id, balance, ... } }
//            Use for eager-loading related records you need right now.
//
// They CANNOT be used together at the same query level.
// But you CAN put a select inside an include (as Paytm's account.js does):
//   include: {
//     sender:   { select: { firstName: true, lastName: true } },
//     receiver: { select: { firstName: true, lastName: true } }
//   }
// This gives you all Transaction fields + only the name fields from User.

console.log("Q5: select = sparse (only listed fields). include = all fields + relation.");
console.log("    Cannot mix at the same level. Can nest select inside include.\n");

// ───────────────────────────────────────────────────────────────
// DEMO — Reference Card
// ───────────────────────────────────────────────────────────────

function runDemo(): void {
    console.log("╔══════════════════════════════════════════════════════════════════╗");
    console.log("║              PRISMA ORM — QUICK REFERENCE CARD                  ║");
    console.log("╠══════════════════════════════════════════════════════════════════╣");
    console.log("║  SCHEMA.PRISMA                                                   ║");
    console.log("║  @id @default(cuid())    → primary key, collision-resistant ID   ║");
    console.log("║  @unique                 → unique column constraint              ║");
    console.log("║  @default(now())         → timestamp at insert                  ║");
    console.log("║  @updatedAt              → auto-set on every update             ║");
    console.log("║  Decimal @db.Decimal(p,s)→ exact decimal (use for money)        ║");
    console.log("║  @map / @@map            → rename column / table in DB          ║");
    console.log("║  @@index / @@unique      → composite indexes / constraints      ║");
    console.log("╠══════════════════════════════════════════════════════════════════╣");
    console.log("║  RELATIONS                                                       ║");
    console.log("║  One-to-One    → @unique on FK in child model                  ║");
    console.log("║  One-to-Many   → no @unique on FK; Post[] on parent            ║");
    console.log("║  Many-to-Many  → Post[] + Tag[] (implicit) or junction model   ║");
    console.log("║  Named         → @relation('Name') when same model appears 2x  ║");
    console.log("║  onDelete      → Cascade | Restrict | SetNull | NoAction       ║");
    console.log("╠══════════════════════════════════════════════════════════════════╣");
    console.log("║  MIGRATIONS                                                      ║");
    console.log("║  migrate dev    → generate + apply + generate client (dev)      ║");
    console.log("║  migrate deploy → apply existing migrations only (prod/CI)      ║");
    console.log("║  db push        → push without migration files (prototype only) ║");
    console.log("║  migrate status → show pending / applied migrations             ║");
    console.log("╠══════════════════════════════════════════════════════════════════╣");
    console.log("║  CRUD                                                            ║");
    console.log("║  findUnique / findFirst / findMany                              ║");
    console.log("║  create / createMany                                            ║");
    console.log("║  update / updateMany                                            ║");
    console.log("║  upsert                                                         ║");
    console.log("║  delete / deleteMany                                            ║");
    console.log("║  select → sparse fields only                                    ║");
    console.log("║  include → all fields + eager-loaded relations                  ║");
    console.log("╠══════════════════════════════════════════════════════════════════╣");
    console.log("║  TRANSACTIONS                                                    ║");
    console.log("║  $transaction([...ops])         → sequential batch, atomic      ║");
    console.log("║  $transaction(async (tx) => {}) → interactive, conditional      ║");
    console.log("║  Paytm: debit + credit + log in one interactive transaction     ║");
    console.log("╠══════════════════════════════════════════════════════════════════╣");
    console.log("║  ADVANCED QUERIES                                                ║");
    console.log("║  orderBy: [{ field: 'desc' }, { field2: 'asc' }]               ║");
    console.log("║  take + skip                → offset pagination                 ║");
    console.log("║  take + cursor              → cursor pagination (fast at scale) ║");
    console.log("║  distinct: ['field']        → deduplicate by field              ║");
    console.log("║  aggregate: { _sum, _avg, _count, _min, _max }                 ║");
    console.log("║  groupBy: { by: ['field'], _sum: { amount: true } }             ║");
    console.log("╠══════════════════════════════════════════════════════════════════╣");
    console.log("║  PRODUCTION                                                      ║");
    console.log("║  Singleton PrismaClient   → one instance per process           ║");
    console.log("║  PgBouncer / Accelerate   → connection pooling for serverless   ║");
    console.log("║  $disconnect()            → call in afterAll() for tests        ║");
    console.log("║  log: ['query']           → dev | log: ['error'] → prod        ║");
    console.log("║  Soft delete middleware   → convert delete → update deletedAt   ║");
    console.log("╚══════════════════════════════════════════════════════════════════╝");
}

runDemo();

export default runDemo;
